new_user_event = {
    u'object': {
        u'username': u'test@example.com',
        u'objectId': u'f9sfvzL8TT',
        u'hasUsedFriends': False,
        u'hasUsedProfile': False,
        u'className': u'_User',
        u'userFirstName': u'John',
        u'userLastName': u'Doe',
        u'updatedAt': u'2016-07-25T21:33:15.748Z',
        u'email': u'test@example.com',
        u'createdAt': u'2016-07-25T21:33:15.748Z',
    },
    u'master': False,
    u'user': {
        u'username': u'test@example.com',
        u'objectId': u'f9sfvzL8TT',
        u'hasUsedFriends': False,
        u'hasUsedProfile': False,
        u'userFirstName': u'John',
        u'userLastName': u'Doe',
        u'updatedAt': u'2016-07-25T21:33:15.748Z',
        u'email': u'test@example.com',
        u'createdAt': u'2016-07-25T21:33:15.748Z',
    },
    u'triggerName': u'afterSave',
    u'installationId': u'8786e2c7-3e64-47b2-9fab-17b93a2425a3',
    u'original': None,
}

update_user_event = {
    u'installationId': u'5cd74c97-7d76-048d-e7a3-8f8bfba684c2',
    u'object': {
        u'username': u'new@example.com',
        u'objectId': u'u2Jd1EPPlB',
        u'hasUsedFriends': False,
        u'hasUsedProfile': False,
        u'className': u'_User',
        u'userFirstName': u'John',
        u'userLastName': u'Doe',
        u'updatedAt': u'2016-07-25T20:44:37.630Z',
        u'email': u'new@example.com',
        u'createdAt': u'2016-07-25T20:24:07.971Z',
    },
    u'master': True,
    u'original': {
        u'username': u'test@example.com',
        u'objectId': u'u2Jd1EPPlB',
        u'hasUsedFriends': False,
        u'hasUsedProfile': False,
        u'className': u'_User',
        u'userFirstName': u'John',
        u'userLastName': u'Doe',
        u'updatedAt': u'2016-07-25T20:43:32.687Z',
        u'email': u'test@example.com',
        u'createdAt': u'2016-07-25T20:24:07.971Z',
    },
    u'triggerName': u'afterSave',
}
